name: Firebase Functions Deploy

on:
  push:
    branches:
      - main  # Select the branch you are working on (e.g., main or master)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Set the Node.js version to 14

    - name: Install dependencies
      run: |
        cd functions
        npm install

    - name: Deploy to Firebase
      uses: wzieba/Firebase-Action@v2
      with:
        firebase_token: ${{ secrets.FIREBASE_TOKEN }}
