name: Firebase Functions Deploy

on:
  push:
    branches:
      - main  # اختر الفرع الذي يعمل عليه فريقك (مثال: main أو master)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # تحديد الإصدار الذي تعمل به

    - name: Install dependencies
      run: |
        cd functions
        npm install

    - name: Deploy to Firebase
      uses: wzieba/Firebase-Action@v2
      with:
        firebase_token: ${{ secrets.FIREBASE_TOKEN }}
