name: Firebase Functions Deploy

on:
  push:
    branches:
      - main  # اختر الفرع الذي تعمل عليه (مثال: main أو master)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # تحديث الإصدار إلى 18

    - name: Install dependencies
      run: |
        cd functions
        npm install

    - name: Install Firebase CLI
      run: npm install -g firebase-tools  # تثبيت Firebase CLI

    - name: Deploy to Firebase
      run: firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}  # استخدام Firebase CLI للنشر
