name: Firebase Functions Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd functions
        npm install

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Set GOOGLE_APPLICATION_CREDENTIALS
      run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/.firebase-service-account.json

    - name: Deploy to Firebase
      run: firebase deploy --only functions --project building-finance-fund --token ${{ secrets.FIREBASE_TOKEN }}
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/.firebase-service-account.json
